# Generated by Django 5.2.8 on 2026-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prductmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_clr', models.CharField(max_length=20)),
                ('prduct_price', models.IntegerField()),
            ],
        ),
    ]
